"""Add order column to groups table

Revision ID: 0f698424d1d9
Revises: 
Create Date: 2025-05-18 02:49:46.811209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f698424d1d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_state_current_month', table_name='attendance_state')
    op.drop_index('ix_attendance_state_id', table_name='attendance_state')
    op.drop_table('attendance_state')
    op.add_column('groups', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'order')
    op.create_table('attendance_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('current_month', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_state_id', 'attendance_state', ['id'], unique=False)
    op.create_index('ix_attendance_state_current_month', 'attendance_state', ['current_month'], unique=False)
    # ### end Alembic commands ###
