"""Add order and category columns to locations table

Revision ID: 8a2f228c71d0
Revises: d2f1b73372b8
Create Date: 2025-05-18 11:54:49.520923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2f228c71d0'
down_revision: Union[str, None] = 'd2f1b73372b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('category', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_locations_category'), 'locations', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_category'), table_name='locations')
    op.drop_column('locations', 'order')
    op.drop_column('locations', 'category')
    # ### end Alembic commands ###
