"""add_note_field_to_attendance

Revision ID: bdbed9dbd6c9
Revises: 8a2f228c71d0
Create Date: 2025-05-18 14:08:51.297866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbed9dbd6c9'
down_revision: Union[str, None] = '8a2f228c71d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'note')
    # ### end Alembic commands ###
