services:
  sokora:
    container_name: sokora
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - ${SERVICE_PORT}:8000
    volumes:
      - ./data/work_entries.csv:/app/work_entries.csv
