services:
  sokora:
    container_name: sokora-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - '${SERVICE_PORT:-8000}:8000'
    volumes:
      # アプリケーションコード（メイン）
      - ../app:/app/app

      # 開発用データ
      - ../data:/app/data

      # プロジェクトファイル
      - ../pyproject.toml:/app/pyproject.toml
      - ../poetry.lock:/app/poetry.lock
      - ../README.md:/app/README.md

      # ドキュメント・スクリプト・設定
      - ../docs:/app/docs
      - ../scripts:/app/scripts
      - ../builder:/app/builder

      # 開発環境設定
      - ../.cursor:/app/.cursor
      - ../.git:/app/.git
      - ../.gitignore:/app/.gitignore
      - ../.prettierrc:/app/.prettierrc
      - ../.devcontainer:/app/.devcontainer
      - ../Dockerfile:/app/Dockerfile
      - ../docker-compose.yml:/app/docker-compose.yml
      - ../.env.sample:/app/.env.sample
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
